dist: trusty
sudo: required
language: python
python:
    - "3.6"
install:
    - bash scripts/travis/travis-build.bash
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
services:
    - postgresql
script: bash scripts/travis/travis-run.sh
before_install:
    - pip install codecov
before_script:
  - psql -c "create role pyfulcrum superuser login password 'pyfulcrum';" -U postgres
  - psql -c 'create database pyfulcrum_test;' -U postgres
  - psql -c 'create extension postgis;' -U pyfulcrum -d pyfulcrum_test

after_success:
    - codecov
